employee_name=input("Enter the employee name: ")
basic_salary = float(input("Enter the basic salary: "))
transport_allowance = float(input("Enter the transport allowance: "))
food_allowance = float(input("Enter the food allowance: "))
gross_salary = basic_salary + transport_allowance + food_allowance
print("===============================")
print("     EMPLOYEE PAYSLIP    ")
print("================================")
print()
print(f'Employee: {employee_name}')
print()
print(f'Basic Salary:      {basic_salary}')
print(f'Transport Allowance:    {transport_allowance}')
print(f'Food Allowance:    {food_allowance}')
print("--------------------------------")
print(f'Gross Salary:      {gross_salary}')