customer_name = input("Enter your name: ")
product = input("Enter the product name: ")
price = float(input("Enter the price: "))
quantity = int(input("Enter the quantity: "))
total = price * quantity
print("===============================")
print("      RECEIPT     ")
print()
print(f'Customer: {customer_name}')
print()
print("Product        Price       Qty")
print("------------------------------------ ")
print(f"{product}    {price}     {quantity}")
print()
print(f"Total:    {total}")
print("Thank you for shopping!")
print("===============================")
