name = input("Enter your name: ")
weight = float(input("Enter your weight in kg: "))
height = float(input("Enter your height in meters: "))
BMI = weight / (height ** 2)
print("===============================")
print("     BMI REPORT           ")
print("===============================")
print()
print(f'Name: {name}')
print(f'Weight: {weight} kg')
print(f'Height: {height} m')
print()
print(f'BMI: {BMI:.2f}')
print("================================")