name = input("Name: ")
id = input("ID: ")
department = input("Department: ")
year = int(input("Year: "))
university = input("University: ")
phone = int(input("Phone: "))

print("+-------------------+")
print(f"|{'AKIBA STUDENT CARD':^25}|")
print("+-------------------+")
print(f"| Name: {name}          |")
print(f"| ID: {id}             |")
print(f"| Department: {department}   |")
print(f"| Year: {year}           |")
print(f"| University: {university}   |")
print(f"| Phone: {phone}         |")
print("+-------------------+")