name = input("Enter your name: ")
age = int(input("Enter your age: "))
city = input("Enter your city: ")
university = input("Enter your university: ")
department = input("Enter your department: ")
favorite = input("Enter your favorite programming language: ")
goal = input("Enter your career goal: ")

print("========================================")
print("      STUDENT INTRODUCTION     ")
print()
print(f"My name is {name}.")
print(f"I am {age} years old.")
print(f"I live in {city}.")
print(f"I study {department} at {university}.")
print(f"My favorite programming language is {favorite}.")
print()
print(f"My programming goal:")
print(f"{goal}.")
print()
print("========================================")