name = input("Enter your name: ")
python_score = float(input("Enter your Python score: "))
english_score = float(input("Enter your English score: "))
maths_score = float(input("Enter your Maths score: "))
average = (python_score + english_score + maths_score) / 3
print("===============================")
print("     STUDENT RESULT            ")
print()
print(f'Student: {name}')
print(f'Python: {python_score}')
print(f'English: {english_score}')
print(f'Maths: {maths_score}')
print("---------------")
print(f'Average:  {average:.2f}')
